name: gcms-analysis
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gensim >=3.8.0
  - matplotlib
  - numba >=0.47
  - numpy
  - pip
  - pyteomics >=4.2
  - python >=3.7,<3.8
  - pyyaml
  - rdkit >=2020.03.1
  - scipy
  - jupyterlab
